package ph.edu.htcgsc.serviceportal.servlet;
import com.google.gson.*; import jakarta.servlet.http.*; import ph.edu.htcgsc.serviceportal.dao.ServiceRequestDraftDAO; import ph.edu.htcgsc.serviceportal.dto.CreateServiceRequestRequest; import ph.edu.htcgsc.serviceportal.util.*; import java.io.*; import java.util.*;
public class ServiceRequestDraftServlet extends HttpServlet {
    private final Gson gson=new Gson(); private final ServiceRequestDraftDAO dao=new ServiceRequestDraftDAO();
    protected void doGet(HttpServletRequest q,HttpServletResponse r)throws IOException{prep(r);Integer uid=auth(q,r,false);if(uid==null)return;try{send(r,200,Map.of("success",true,"drafts",dao.list(uid)));}catch(Exception e){err(r,500,"Unable to load drafts.");}}
    protected void doPost(HttpServletRequest q,HttpServletResponse r)throws IOException{prep(r);Integer uid=auth(q,r,true);if(uid==null)return;try{CreateServiceRequestRequest d=gson.fromJson(q.getReader(),CreateServiceRequestRequest.class);Map<String,String> ve=ServiceRequestDraftValidator.validateAndNormalize(d);if(!ve.isEmpty()){send(r,400,Map.of("success",false,"message","Draft contains invalid values.","validationErrors",ve));return;}send(r,201,Map.of("success",true,"message","Draft saved.","draft",dao.create(uid,d)));}catch(Exception e){err(r,500,"Unable to save draft.");}}
    protected void doPut(HttpServletRequest q,HttpServletResponse r)throws IOException{prep(r);Integer uid=auth(q,r,true);if(uid==null)return;Long id=id(q,r);if(id==null)return;try{CreateServiceRequestRequest d=gson.fromJson(q.getReader(),CreateServiceRequestRequest.class);Map<String,String> ve=ServiceRequestDraftValidator.validateAndNormalize(d);if(!ve.isEmpty()){send(r,400,Map.of("success",false,"message","Draft contains invalid values.","validationErrors",ve));return;}var draft=dao.update(id,uid,d);if(draft==null){err(r,404,"Draft not found or not owned by this requester.");return;}send(r,200,Map.of("success",true,"message","Draft updated.","draft",draft));}catch(Exception e){err(r,500,"Unable to update draft.");}}
    protected void doDelete(HttpServletRequest q,HttpServletResponse r)throws IOException{prep(r);Integer uid=auth(q,r,true);if(uid==null)return;Long id=id(q,r);if(id==null)return;try{if(!dao.delete(id,uid)){err(r,404,"Draft not found or not owned by this requester.");return;}send(r,200,Map.of("success",true,"message","Draft permanently deleted."));}catch(Exception e){err(r,500,"Unable to delete draft.");}}
    private Integer auth(HttpServletRequest q,HttpServletResponse r,boolean csrf)throws IOException{if(!SessionUtil.isAuthenticated(q)){err(r,401,"Authentication is required.");return null;}if(!SessionUtil.isRequester(q)){err(r,403,"Only requester accounts may manage drafts.");return null;}if(csrf&&!CsrfUtil.isRequestTokenValid(q)){err(r,403,"The security token is missing or invalid.");return null;}return SessionUtil.getAuthenticatedPersonnelId(q);}
    private Long id(HttpServletRequest q,HttpServletResponse r)throws IOException{try{long v=Long.parseLong(q.getParameter("id"));if(v<=0)throw new Exception();return v;}catch(Exception e){err(r,400,"A valid draft id is required.");return null;}}
    private void prep(HttpServletResponse r){r.setContentType("application/json");r.setCharacterEncoding("UTF-8");r.setHeader("Cache-Control","no-store");}
    private void err(HttpServletResponse r,int c,String m)throws IOException{send(r,c,Map.of("success",false,"message",m));} private void send(HttpServletResponse r,int c,Object b)throws IOException{r.setStatus(c);r.getWriter().write(gson.toJson(b));}
}
