-- Migration 010: Persistent in-application notifications
-- Notifications are generated by the Java backend.
-- Users may only retrieve and update their own notifications.
-- Safe to rerun. Existing records are not deleted or modified.

USE htc_service_portal;

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    Notification_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    Recipient_ID INT UNSIGNED NOT NULL,
    Triggered_By_ID INT UNSIGNED NULL,

    Request_ID BIGINT UNSIGNED NULL,
    Work_Order_ID BIGINT UNSIGNED NULL,

    Notification_Type VARCHAR(50) NOT NULL,
    Notification_Title VARCHAR(150) NOT NULL,
    Notification_Message VARCHAR(1000) NOT NULL,

    -- Optional internal application path, never an external URL.
    Action_URL VARCHAR(255) NULL,

    -- Used by the backend to prevent duplicate notifications
    -- when the same operation is safely retried.
    Notification_Event_Key VARCHAR(150) NULL,

    Is_Read BOOLEAN NOT NULL DEFAULT FALSE,
    Read_At TIMESTAMP NULL DEFAULT NULL,

    Created_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (Notification_ID),

    CONSTRAINT UQ_NOTIFICATION_RECIPIENT_EVENT
        UNIQUE (Recipient_ID, Notification_Event_Key),

    INDEX IX_NOTIFICATION_RECIPIENT_READ (
        Recipient_ID,
        Is_Read,
        Created_At
    ),

    INDEX IX_NOTIFICATION_REQUEST (
        Request_ID,
        Created_At
    ),

    INDEX IX_NOTIFICATION_WORK_ORDER (
        Work_Order_ID,
        Created_At
    ),

    INDEX IX_NOTIFICATION_TYPE (
        Notification_Type,
        Created_At
    ),

    CONSTRAINT FK_NOTIFICATION_RECIPIENT
        FOREIGN KEY (Recipient_ID)
        REFERENCES SCHOOL_PERSONNEL (Personnel_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT FK_NOTIFICATION_TRIGGERED_BY
        FOREIGN KEY (Triggered_By_ID)
        REFERENCES SCHOOL_PERSONNEL (Personnel_ID)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT FK_NOTIFICATION_REQUEST
        FOREIGN KEY (Request_ID)
        REFERENCES SERVICE_REQUEST (Request_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT FK_NOTIFICATION_WORK_ORDER
        FOREIGN KEY (Work_Order_ID)
        REFERENCES WORK_ORDER (Work_Order_ID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT CHK_NOTIFICATION_TYPE
        CHECK (
            Notification_Type IN (
                'ACCOUNT_APPROVAL_REQUIRED',
                'ACCOUNT_APPROVED',
                'ACCOUNT_REJECTED',
                'REQUEST_SUBMITTED',
                'AI_RECOMMENDATION_READY',
                'AI_RECOMMENDATION_UNAVAILABLE',
                'REQUEST_UNDER_REVIEW',
                'APPROVAL_REQUIRED',
                'REQUEST_APPROVED',
                'REQUEST_REJECTED',
                'REQUEST_MARKED_DUPLICATE',
                'REQUEST_CANCELLED',
                'WORK_ORDER_CREATED',
                'TECHNICIAN_ASSIGNED',
                'TECHNICIAN_REASSIGNED',
                'WORK_ACKNOWLEDGED',
                'WORK_STARTED',
                'WORK_PROGRESS_UPDATED',
                'WORK_ON_HOLD',
                'WORK_RESUMED',
                'WORK_COMPLETED',
                'WORK_VERIFIED',
                'REQUEST_CLOSED'
            )
        ),

    CONSTRAINT CHK_NOTIFICATION_TITLE
        CHECK (
            CHAR_LENGTH(TRIM(Notification_Title))
            BETWEEN 3 AND 150
        ),

    CONSTRAINT CHK_NOTIFICATION_MESSAGE
        CHECK (
            CHAR_LENGTH(TRIM(Notification_Message))
            BETWEEN 3 AND 1000
        ),

    CONSTRAINT CHK_NOTIFICATION_ACTION_URL
        CHECK (
            Action_URL IS NULL
            OR (
                CHAR_LENGTH(TRIM(Action_URL))
                    BETWEEN 1 AND 255
                AND LEFT(TRIM(Action_URL), 1)
                    IN ('/', '#', '?')
            )
        ),

    CONSTRAINT CHK_NOTIFICATION_EVENT_KEY
        CHECK (
            Notification_Event_Key IS NULL
            OR CHAR_LENGTH(TRIM(Notification_Event_Key))
                BETWEEN 3 AND 150
        ),

    CONSTRAINT CHK_NOTIFICATION_READ_STATE
        CHECK (
            (
                Is_Read = FALSE
                AND Read_At IS NULL
            )
            OR
            (
                Is_Read = TRUE
                AND Read_At IS NOT NULL
            )
        )
) ENGINE = InnoDB;

SHOW CREATE TABLE NOTIFICATION;

SELECT
    TABLE_NAME,
    ENGINE,
    TABLE_COLLATION
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'NOTIFICATION';

SELECT
    COUNT(*) AS Existing_Notification_Count
FROM NOTIFICATION;