-- Task 8: requester-owned drafts provide safe literal CRUD without deleting official audited requests.
CREATE TABLE IF NOT EXISTS SERVICE_REQUEST_DRAFT (
    Draft_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    Requester_ID INT UNSIGNED NOT NULL,
    Requested_Category_ID TINYINT UNSIGNED NULL,
    Preferred_Priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
    Title VARCHAR(160) NOT NULL,
    Description VARCHAR(3000) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Date_Reported DATE NOT NULL,
    Created_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Draft_ID),
    KEY IX_DRAFT_REQUESTER (Requester_ID, Updated_At),
    CONSTRAINT FK_DRAFT_REQUESTER FOREIGN KEY (Requester_ID) REFERENCES SCHOOL_PERSONNEL(Personnel_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT FK_DRAFT_CATEGORY FOREIGN KEY (Requested_Category_ID) REFERENCES SERVICE_CATEGORY(Category_ID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;

