USE htc_service_portal;

ALTER TABLE SERVICE_REQUEST_DRAFT
    MODIFY COLUMN Preferred_Priority VARCHAR(20) NULL DEFAULT NULL,
    MODIFY COLUMN Title VARCHAR(150) NULL DEFAULT NULL,
    MODIFY COLUMN Description TEXT NULL,
    MODIFY COLUMN Location VARCHAR(120) NULL DEFAULT NULL,
    MODIFY COLUMN Date_Reported DATE NULL DEFAULT NULL;
